version: 1.0.{build}
branches:
  only:
  - master
  - develop
os: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x64
clone_folder: C:\projects\hdrview
install:
  - git submodule update --init --recursive
before_build:
  - cmake -DCMAKE_BUILD_TYPE=%Configuration% -DBOOST_ROOT=C:\Libraries\boost_1_64_0 -G "Visual Studio 15 2017 Win64" .
build_script:
  - cmake --build . --target ALL_BUILD --config %Configuration% --parallel 4
on_success:
  - cmd: 7z a HDRView_x64.7z "C:\projects\hdrview\%Configuration%\*.exe"
  - cmd: appveyor PushArtifact HDRView_x64.7z
test: off
